services:
  postgres:
    image: pgvector/pgvector:0.6.2-pg16
    container_name: pgvector-postgres
    environment:
      POSTGRES_DB: medquery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: medquery-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    mem_limit: 4g
    mem_reservation: 1g
    environment:
      - PYTHONHASHSEED=0
      - MALLOC_ARENA_MAX=2

volumes:
  pgvector_data:
